"""Users, devices and authentication tokens."""
from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    Boolean,
    Enum as SAEnum,
    ForeignKey,
    Index,
    Integer,
    String,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base, TimestampMixin, UTCDateTime
from app.models.enums import Role

if TYPE_CHECKING:
    from app.models.org import Department, WorkSchedule
    from app.models.session import WorkSession


class User(Base, TimestampMixin):
    __tablename__ = "users"
    __table_args__ = (
        Index("ix_users_department_role", "department_id", "role"),
        Index("ix_users_team_leader", "team_leader_id"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    employee_code: Mapped[str] = mapped_column(String(32), unique=True, nullable=False)
    username: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    full_name: Mapped[str] = mapped_column(String(160), nullable=False)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    role: Mapped[Role] = mapped_column(
        SAEnum(Role, native_enum=False, length=20), default=Role.EMPLOYEE, nullable=False
    )

    department_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("departments.id", ondelete="SET NULL")
    )
    # The person who receives this employee's inactivity / offline alerts.
    team_leader_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )
    schedule_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("work_schedules.id", ondelete="SET NULL")
    )

    timezone: Mapped[str] = mapped_column(String(64), default="UTC", nullable=False)
    phone: Mapped[Optional[str]] = mapped_column(String(32))
    slack_user_id: Mapped[Optional[str]] = mapped_column(String(64))

    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    must_change_password: Mapped[bool] = mapped_column(
        Boolean, default=True, nullable=False
    )
    # Recorded when the employee accepts the monitoring disclosure in the agent.
    monitoring_notice_accepted_at: Mapped[Optional[datetime]] = mapped_column(
        UTCDateTime
    )
    failed_login_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    locked_until: Mapped[Optional[datetime]] = mapped_column(UTCDateTime)
    last_login_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime)
    deactivated_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime)

    department: Mapped[Optional["Department"]] = relationship(
        back_populates="members", foreign_keys=[department_id]
    )
    schedule: Mapped[Optional["WorkSchedule"]] = relationship(foreign_keys=[schedule_id])
    team_leader: Mapped[Optional["User"]] = relationship(
        remote_side=[id], foreign_keys=[team_leader_id], back_populates="team_members"
    )
    team_members: Mapped[list["User"]] = relationship(
        back_populates="team_leader", foreign_keys=[team_leader_id]
    )
    devices: Mapped[list["Device"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    # WorkSession also carries edited_by_id -> users, so the join must be explicit.
    work_sessions: Mapped[list["WorkSession"]] = relationship(
        back_populates="user",
        cascade="all, delete-orphan",
        foreign_keys="WorkSession.user_id",
    )

    @property
    def is_admin(self) -> bool:
        return self.role is Role.ADMIN

    @property
    def is_manager(self) -> bool:
        return self.role in (Role.ADMIN, Role.TEAM_LEADER)

    @property
    def first_name(self) -> str:
        return self.full_name.split(" ")[0] if self.full_name else self.username

    def __repr__(self) -> str:  # pragma: no cover
        return f"<User {self.username} ({self.role.value})>"


class Device(Base, TimestampMixin):
    """A company laptop running the tracking agent.

    Devices are enrolled once, then authenticate with a long-lived token so the
    agent can keep reporting after a reboot without re-prompting for a password.
    """

    __tablename__ = "devices"
    __table_args__ = (Index("ix_devices_user_active", "user_id", "is_active"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    # Stable hardware fingerprint generated by the agent on first run.
    device_uid: Mapped[str] = mapped_column(String(128), unique=True, nullable=False)
    token_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    hostname: Mapped[Optional[str]] = mapped_column(String(160))
    platform: Mapped[Optional[str]] = mapped_column(String(64))
    os_version: Mapped[Optional[str]] = mapped_column(String(120))
    agent_version: Mapped[Optional[str]] = mapped_column(String(32))

    last_seen_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime)
    last_ip: Mapped[Optional[str]] = mapped_column(String(64))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    revoked_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime)

    user: Mapped["User"] = relationship(back_populates="devices")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Device {self.hostname or self.device_uid[:12]}>"


class RefreshToken(Base, TimestampMixin):
    """Rotating refresh tokens for dashboard sessions."""

    __tablename__ = "refresh_tokens"
    __table_args__ = (Index("ix_refresh_user_revoked", "user_id", "revoked_at"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    token_hash: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(UTCDateTime, nullable=False)
    revoked_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime)
    user_agent: Mapped[Optional[str]] = mapped_column(String(255))
    ip_address: Mapped[Optional[str]] = mapped_column(String(64))

    user: Mapped["User"] = relationship()


class EnrollmentCode(Base, TimestampMixin):
    """Single-use code an admin hands to a laptop to bind it to an employee."""

    __tablename__ = "enrollment_codes"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    code_hash: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(UTCDateTime, nullable=False)
    used_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime)
    created_by_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )

    user: Mapped["User"] = relationship(foreign_keys=[user_id])
