"""Initial schema: users, devices, sessions, activity, alerts, audit

Revision ID: 2ec9c6ebddb6
Revises: 
Create Date: 2026-09-19 12:20:19.339699
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('workdays', sa.String(length=7), nullable=False),
    sa.Column('grace_late_minutes', sa.Integer(), nullable=False),
    sa.Column('grace_early_minutes', sa.Integer(), nullable=False),
    sa.Column('expected_hours_per_day', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_schedules')),
    sa.UniqueConstraint('name', name=op.f('uq_work_schedules_name'))
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_schedule_id', sa.Integer(), nullable=True),
    sa.Column('default_team_leader_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_schedule_id'], ['work_schedules.id'], name=op.f('fk_departments_default_schedule_id_work_schedules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_team_leader_id'], ['users.id'], name='fk_departments_default_team_leader_id_users', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('channel_type', sa.Enum('EMAIL', 'SLACK', 'TEAMS', 'WHATSAPP', 'WEBHOOK', 'DASHBOARD', name='channeltype', native_enum=False, length=20), nullable=False),
    sa.Column('encrypted_config', sa.Text(), nullable=True),
    sa.Column('public_config', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity', native_enum=False, length=16), nullable=False),
    sa.Column('alert_types', sa.JSON(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_notification_channels_department_id_departments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels')),
    sa.UniqueConstraint('name', name=op.f('uq_notification_channels_name'))
    )
    op.create_table('policy_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('idle_threshold_seconds', sa.Integer(), nullable=False),
    sa.Column('idle_realert_seconds', sa.Integer(), nullable=False),
    sa.Column('treat_lock_as_idle', sa.Boolean(), nullable=False),
    sa.Column('short_break_max_seconds', sa.Integer(), nullable=False),
    sa.Column('lunch_break_max_seconds', sa.Integer(), nullable=False),
    sa.Column('break_overrun_grace_seconds', sa.Integer(), nullable=False),
    sa.Column('short_breaks_per_day', sa.Integer(), nullable=False),
    sa.Column('lunch_breaks_per_day', sa.Integer(), nullable=False),
    sa.Column('auto_end_expired_breaks', sa.Boolean(), nullable=False),
    sa.Column('heartbeat_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('heartbeat_grace_seconds', sa.Integer(), nullable=False),
    sa.Column('offline_alert_after_seconds', sa.Integer(), nullable=False),
    sa.Column('auto_clock_out_after_hours', sa.Integer(), nullable=False),
    sa.Column('alert_on_late_arrival', sa.Boolean(), nullable=False),
    sa.Column('alert_on_early_departure', sa.Boolean(), nullable=False),
    sa.Column('alert_on_no_show', sa.Boolean(), nullable=False),
    sa.Column('no_show_after_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_policy_settings_department_id_departments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_settings')),
    sa.UniqueConstraint('department_id', name='uq_policy_department')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEAM_LEADER', 'EMPLOYEE', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('team_leader_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('slack_user_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('monitoring_notice_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['work_schedules.id'], name=op.f('fk_users_schedule_id_work_schedules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_leader_id'], ['users.id'], name=op.f('fk_users_team_leader_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('employee_code', name=op.f('uq_users_employee_code')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_department_role', ['department_id', 'role'], unique=False)
        batch_op.create_index('ix_users_team_leader', ['team_leader_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor_time', ['actor_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_uid', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=160), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('os_version', sa.String(length=120), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ip', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('device_uid', name=op.f('uq_devices_device_uid'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index('ix_devices_user_active', ['user_id', 'is_active'], unique=False)

    op.create_table('enrollment_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_enrollment_codes_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_enrollment_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment_codes')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_enrollment_codes_code_hash'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_refresh_user_revoked', ['user_id', 'revoked_at'], unique=False)

    op.create_table('work_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('clock_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clock_out_reason', sa.Enum('MANUAL', 'AUTO_SCHEDULE', 'ADMIN', 'OFFLINE_TIMEOUT', name='clockoutreason', native_enum=False, length=24), nullable=True),
    sa.Column('active_seconds', sa.Integer(), nullable=False),
    sa.Column('idle_seconds', sa.Integer(), nullable=False),
    sa.Column('locked_seconds', sa.Integer(), nullable=False),
    sa.Column('lunch_seconds', sa.Integer(), nullable=False),
    sa.Column('short_break_seconds', sa.Integer(), nullable=False),
    sa.Column('offline_seconds', sa.Integer(), nullable=False),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_late_arrival', sa.Boolean(), nullable=False),
    sa.Column('late_by_seconds', sa.Integer(), nullable=False),
    sa.Column('is_early_departure', sa.Boolean(), nullable=False),
    sa.Column('early_by_seconds', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_state', sa.Enum('ACTIVE', 'IDLE', 'LOCKED', 'BREAK_LUNCH', 'BREAK_SHORT', 'OFFLINE', name='activitystate', native_enum=False, length=20), nullable=False),
    sa.Column('state_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_offline', sa.Boolean(), nullable=False),
    sa.Column('offline_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('edited_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_work_sessions_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], name=op.f('fk_work_sessions_edited_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_work_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_sessions'))
    )
    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_heartbeat', ['clock_out_at', 'last_heartbeat_at'], unique=False)
        batch_op.create_index('ix_sessions_open', ['user_id', 'clock_out_at'], unique=False)
        batch_op.create_index('ix_sessions_user_date', ['user_id', 'work_date'], unique=False)

    op.create_table('activity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('CLOCK_IN', 'CLOCK_OUT', 'BREAK_START', 'BREAK_END', 'BREAK_OVERRUN', 'IDLE_START', 'IDLE_END', 'SCREEN_LOCKED', 'SCREEN_UNLOCKED', 'AGENT_STARTED', 'AGENT_STOPPED', 'SYSTEM_SUSPEND', 'SYSTEM_RESUME', 'SYSTEM_SHUTDOWN', 'HEARTBEAT_LOST', 'RECONNECTED', 'LATE_ARRIVAL', 'EARLY_DEPARTURE', name='eventtype', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.Enum('AGENT', 'SERVER', 'ADMIN', name='eventsource', native_enum=False, length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_activity_events_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['work_sessions.id'], name=op.f('fk_activity_events_session_id_work_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_events'))
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_session', ['session_id'], unique=False)
        batch_op.create_index('ix_events_type_time', ['event_type', 'occurred_at'], unique=False)
        batch_op.create_index('ix_events_user_time', ['user_id', 'occurred_at'], unique=False)

    op.create_table('activity_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'IDLE', 'LOCKED', 'BREAK_LUNCH', 'BREAK_SHORT', 'OFFLINE', name='activitystate', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['work_sessions.id'], name=op.f('fk_activity_intervals_session_id_work_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_intervals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_intervals'))
    )
    with op.batch_alter_table('activity_intervals', schema=None) as batch_op:
        batch_op.create_index('ix_intervals_open', ['session_id', 'ended_at'], unique=False)
        batch_op.create_index('ix_intervals_session_start', ['session_id', 'started_at'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.Enum('IDLE_NO_BREAK', 'BREAK_OVERRUN', 'AGENT_OFFLINE', 'AGENT_TERMINATED', 'LATE_ARRIVAL', 'EARLY_DEPARTURE', 'MISSING_CLOCK_OUT', 'NO_SHOW', name='alerttype', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity', native_enum=False, length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('acknowledgement_note', sa.Text(), nullable=True),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], name=op.f('fk_alerts_acknowledged_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_alerts_recipient_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['work_sessions.id'], name=op.f('fk_alerts_session_id_work_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], name=op.f('fk_alerts_subject_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_dedup', ['dedup_key'], unique=True)
        batch_op.create_index('ix_alerts_recipient_ack', ['recipient_id', 'acknowledged_at'], unique=False)
        batch_op.create_index('ix_alerts_subject_time', ['subject_id', 'triggered_at'], unique=False)

    op.create_table('break_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('break_type', sa.Enum('LUNCH', 'SHORT', name='breaktype', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.Enum('MANUAL', 'AUTO_EXPIRED', 'SESSION_END', 'ADMIN', name='breakendreason', native_enum=False, length=24), nullable=True),
    sa.Column('allowed_seconds', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('overrun_seconds', sa.Integer(), nullable=False),
    sa.Column('overrun_alert_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['work_sessions.id'], name=op.f('fk_break_periods_session_id_work_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_break_periods_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_break_periods'))
    )
    with op.batch_alter_table('break_periods', schema=None) as batch_op:
        batch_op.create_index('ix_breaks_session_open', ['session_id', 'ended_at'], unique=False)
        batch_op.create_index('ix_breaks_user_date', ['user_id', 'started_at'], unique=False)

    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('channel_type', sa.Enum('EMAIL', 'SLACK', 'TEAMS', 'WHATSAPP', 'WEBHOOK', 'DASHBOARD', name='channeltype', native_enum=False, length=20), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SKIPPED', name='deliverystatus', native_enum=False, length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_notification_deliveries_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], name=op.f('fk_notification_deliveries_channel_id_notification_channels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries'))
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_deliveries_status_next', ['status', 'next_attempt_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_deliveries_status_next')

    op.drop_table('notification_deliveries')
    with op.batch_alter_table('break_periods', schema=None) as batch_op:
        batch_op.drop_index('ix_breaks_user_date')
        batch_op.drop_index('ix_breaks_session_open')

    op.drop_table('break_periods')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_subject_time')
        batch_op.drop_index('ix_alerts_recipient_ack')
        batch_op.drop_index('ix_alerts_dedup')

    op.drop_table('alerts')
    with op.batch_alter_table('activity_intervals', schema=None) as batch_op:
        batch_op.drop_index('ix_intervals_session_start')
        batch_op.drop_index('ix_intervals_open')

    op.drop_table('activity_intervals')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_user_time')
        batch_op.drop_index('ix_events_type_time')
        batch_op.drop_index('ix_events_session')

    op.drop_table('activity_events')
    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_date')
        batch_op.drop_index('ix_sessions_open')
        batch_op.drop_index('ix_sessions_heartbeat')

    op.drop_table('work_sessions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_user_revoked')

    op.drop_table('refresh_tokens')
    op.drop_table('enrollment_codes')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index('ix_devices_user_active')

    op.drop_table('devices')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_entity')
        batch_op.drop_index('ix_audit_actor_time')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_team_leader')
        batch_op.drop_index('ix_users_department_role')

    op.drop_table('users')
    op.drop_table('policy_settings')
    op.drop_table('notification_channels')
    op.drop_table('departments')
    op.drop_table('work_schedules')
    # ### end Alembic commands ###
